apiVersion: apps/v1
kind: Deployment
metadata:
  name: cors-anywhere
spec:
  replicas: 1
  selector:
    matchLabels:
      component: cors-anywhere
  template:
    metadata:
      labels:
        component: cors-anywhere
    spec:
      containers:
        -
          name: cors-anywhere
          image: 'us.gcr.io/nwr-prod-env/cors-anywhere@sha256:80b33bbb6dca04d77bd6196b7068023d30ae6db3e1483d6f39eeb1845462cfe3'
          ports:
            -
              name: cors-anywhere
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /iscorsneeded
              port: cors-anywhere
            initialDelaySeconds: 5
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /iscorsneeded
              port: cors-anywhere
            initialDelaySeconds: 15
            timeoutSeconds: 20

